#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -euf -o pipefail

if [[ "$(uname -s)" == "Linux" ]]; then
	sudo apt-get -y install git
elif [[ "$(uname -s)" == "Darwin" ]]; then
	# install xcode cli tools
	git version
	#xcode-select --install
	read -n1 -r -p "If git works, press any key to continue..." key
fi

DOTFILES=~/dotfiles

git clone https://github.com/jakdept/dotfiles.git ${DOTFILES}

source ${DOTFILES}/functions

info '  Running automatic installation'

echo ''

run_installers

install_dotfiles

GIT_DIR=${DOTFILES}/.git
GIT_WORK_TREE=${DOTFILES}
git remote set-url origin git@github.com:jakdept/dotfiles.git
unset GIT_DIR
unset GIT_WORK_TREE

echo ''
echo '  All installed!'
