#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -euf -o pipefail

DOTFILES=~/dotfiles

source ${DOTFILES}/script/functions

info '  Running manual installation'

echo ''

run_installers

install_dotfiles

echo ''
echo '  All installed!'
