#!/usr/bin/env bash
#
# Run all dotfiles installers.

export DOTFILES=~/dotfiles

[[ ! -d ${DOTFILES} ]] && git clone https://github.com/jakdept/dotfiles.git ${DOTFILES}

source ${DOTFILES}/functions

info '  Running manual installation'

echo ''

run_installers

install_dotfiles

echo ''
echo '  All installed!'
