#!/bin/bash
[[ ! -f hosts ]] && touch hosts
[[ ! -f ansible.cfg ]] && touch ansible.cfg
if [[ $1 == "enter" ]]; then
docker run --rm \
	-it \
	-v ${PWD}/hosts:/etc/ansible/hosts \
	-v ${PWD}/ansible.cfg:/etc/ansible/ansible.cfg \
	-v ${HOME}/.ssh:/root/.ssh:ro \
	r.j3ss.co/ansible /bin/bash
else
docker run --rm \
	-it \
	-v ${PWD}/hosts:/etc/ansible/hosts \
	-v ${PWD}/ansible.cfg:/etc/ansible/ansible.cfg \
	-v ${HOME}/.ssh:/root/.ssh:ro \
	r.j3ss.co/ansible $@
fi
